name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: thegobc/qm-converter:latest

            - name: Copy docker-compose files to server
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: '92.113.25.5'
                  username: 'root'
                  key: ${{ secrets.SSH_PRIVATE_KEY_NOPW }}
                  source: './docker-compose.yml,./docker-compose.swarm.yml'
                  target: '~/qm-converter/'

            - name: SSH and update Docker Swarm service
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: '92.113.25.5'
                  username: 'root'
                  key: ${{ secrets.SSH_PRIVATE_KEY_NOPW }}
                  script: |
                      cd qm-converter
                      docker stack deploy -c docker-compose.yml -c docker-compose.swarm.yml qm-stack
                      docker service update --image thegobc/qm-converter:latest --force qm-stack_qm_converter
